ParkenDD/parkapi-sources-v3

src/parkapi_sources/converters/heidelberg/converter.py

Add `PARK_API_HEIDELBERG_API_KEY`  as required key.

fix: add required key at heidelberg

---

CHANGELOG.md

0.3.0 release

---

src/parkapi_sources/converters/pum_bw/converter.py

Fixes a typing issue introduced at https://github.com/ParkenDD/parkapi-sources-v3/pull/32

fix typing

---

.github/workflows/build-publish.yml
CHANGELOG.md
README.md
pyproject.toml
requirements-dev.txt
requirements.txt

This MR prepares the 0.4.0 release

0.4.0 release with package version updates

---

CHANGELOG.md
src/parkapi_sources/converters/radvis_bw/converter.py

* Fixes purpose to BIKE at RadVIS bike converter

fix radvis purpose

---

CHANGELOG.md
pyproject.toml
requirements.txt

prepare version 0.4.3 release

---

src/parkapi_sources/converters/freiburg/models.py

Fix Freiburg timezone

---

src/parkapi_sources/converters/karlsruhe/models.py

Fixes https://github.com/ParkenDD/parkapi-sources-v3/issues/50

add static capacity to karlsruhe mapping

---

.github/workflows/lint-test.yml
CHANGELOG.md
Makefile
README.md
pyproject.toml
requirements-dev.txt
requirements.txt
src/parkapi_sources/converters/bfrk_bw/base_converter.py
src/parkapi_sources/converters/ellwangen/converter.py
src/parkapi_sources/converters/heidelberg/validators.py
tests/converters/bietigheim_bissingen_test.py
tests/converters/karlsruhe_bike_test.py
tests/converters/karlsruhe_test.py
tests/util/data_xml_helper.py
tox.ini

0.5.0 release: replace black by ruff format, maintenance

0.5.0 release, replace black by ruff format, maintenance

---

CHANGELOG.md
src/parkapi_sources/converters/karlsruhe/models.py

set karlsruhe to realtime

---

.github/workflows/build-publish.yml
CHANGELOG.md
requirements-dev.txt

prepare 0.6.0 release, small updates

---

CHANGELOG.md
src/parkapi_sources/converters/herrenberg/converter.py

... Herrenberg is a pull converter,

Fix Herrenberg base class, version 0.6.1

---

CHANGELOG.md
README.md

version 0.7.0

---

CHANGELOG.md
src/parkapi_sources/converters/ulm/converter.py
tests/converters/data/ulm.html

Resolves https://github.com/ParkenDD/parkapi-sources-v3/issues/80

fix ulm scraper

---

CHANGELOG.md
src/parkapi_sources/converters/herrenberg/models.py

Resolve https://github.com/ParkenDD/parkapi-sources-v3/issues/81

fix Herrenberg address

---

CHANGELOG.md
src/parkapi_sources/converters/herrenberg/models.py

Resolves https://github.com/ParkenDD/parkapi-sources-v3/issues/79

fix herrenberg state mapping

---

src/parkapi_sources/converters/bfrk_bw/bike_converter.py
src/parkapi_sources/converters/bfrk_bw/bike_models.py

Resolves https://github.com/ParkenDD/parkapi-sources-v3/issues/66

fix bfrk is_covered

---

.pre-commit-config.yaml
pyproject.toml
requirements-dev.txt
requirements.txt
src/parkapi_sources/converters/radvis_bw/converter.py
src/parkapi_sources/converters/radvis_bw/models.py
src/parkapi_sources/models/enums.py
src/parkapi_sources/models/parking_site_inputs.py
tests/converters/radvis_bw_test.py

Adds ParkingSite Group Support, eg for connecting lockboxes and bicycle parking sites. Uses this feature at RadVis. Also updates some packages and provides a pre commit hook.

parking site groups

---

src/parkapi_sources/converters/__init__.py
src/parkapi_sources/converters/base_converter/pull/__init__.py
src/parkapi_sources/converters/base_converter/pull/datex2_mixin.py
src/parkapi_sources/converters/stuttgart/converter.py
src/parkapi_sources/converters/vrs/__init__.py
src/parkapi_sources/converters/vrs/converter.py
src/parkapi_sources/parkapi_sources.py
tests/converters/data/vrs_vaihingen-realtime.xml
tests/converters/data/vrs_vaihingen-static.xml
tests/converters/vrs_test.py

Supports multiple DATEX2 sources from VRS via Mobilithek

VRS data via Mobilithek

---

src/parkapi_sources/converters/kienzler/converter.py
tests/converters/kienzler_test.py

Kienzler Env Var Fix

---

src/parkapi_sources/converters/vrs/converter.py

Cuts off additional data in brackets at the uid field

fix vrs uid mapping

---

src/parkapi_sources/converters/apcoa/converter.py
src/parkapi_sources/converters/apcoa/mapper.py
src/parkapi_sources/converters/apcoa/validators.py
tests/converters/apcoa_test.py

Ignore known APCOA Issues

---

src/parkapi_sources/converters/karlsruhe/converter.py
tests/converters/karlsruhe_bike_test.py

Ignore missing capacities at Karlsruhe Bike

Ignore missing capacities at Karlsruhe Bike

---

src/parkapi_sources/converters/bfrk_bw/base_converter.py
src/parkapi_sources/converters/bfrk_bw/bike_converter.py
src/parkapi_sources/converters/bfrk_bw/car_converter.py
tests/converters/bfrk_bw_test.py

make bfrk url configurable

---

src/parkapi_sources/converters/heidelberg/models.py

... because all of them are  not free.

has_fee True at all Heidelberg parking sites

---

src/parkapi_sources/converters/bfrk_bw/bike_models.py
src/parkapi_sources/converters/bfrk_bw/car_models.py

Adds Park and Ride data to BFRK converter

Park and Ride at BFRK

---

src/parkapi_sources/converters/vrs/converter.py

Add VRS data

---

src/parkapi_sources/converters/karlsruhe/models.py
src/parkapi_sources/converters/opendata_swiss/models.py
src/parkapi_sources/converters/radvis_bw/models.py
src/parkapi_sources/models/enums.py

remove generic bike enum

---

src/parkapi_sources/converters/pbw/validation.py

Resolves https://github.com/ParkenDD/parkapi-sources-v3/issues/120

Fix PBW Mapping

---

src/parkapi_sources/converters/heidelberg/models.py

Implements https://github.com/ParkenDD/parkapi-sources-v3/issues/116

Fix Heidelberg fee

---

src/parkapi_sources/converters/bahn_v2/validators.py

Fixes https://github.com/ParkenDD/parkapi-sources-v3/issues/122

fixes bahn mapping

---

src/parkapi_sources/converters/bfrk_bw/bike_models.py

fix bfrk mapping

---

src/parkapi_sources/converters/kienzler/converter.py

Splits Kienzler Requests in chunks of 25 IDs.

split up kienzler requests

---

src/parkapi_sources/converters/apcoa/mapper.py
src/parkapi_sources/converters/bahn_v2/mapper.py
src/parkapi_sources/converters/base_converter/push/normalized_xlsx_converter.py
src/parkapi_sources/converters/base_converter/push/xlsx_converter.py
src/parkapi_sources/converters/bfrk_bw/base_models.py
src/parkapi_sources/converters/bfrk_bw/bike_models.py
src/parkapi_sources/converters/bfrk_bw/car_models.py
src/parkapi_sources/converters/huefner/converter.py
src/parkapi_sources/converters/opendata_swiss/models.py
src/parkapi_sources/models/parking_site_inputs.py
src/parkapi_sources/models/xlsx_inputs.py
tests/converters/huefner_test.py

Capacity is a mandatory field. A check for this was missing in our tests.

enforce capacity

---

src/parkapi_sources/converters/herrenberg/models.py

`fee_description` was not helpful, so we remove it

remove confusing herrenberg field

---

src/parkapi_sources/converters/kienzler/converter.py
src/parkapi_sources/converters/kienzler/models.py

Can be calculated by base url and id

set kienzler public url

---

src/parkapi_sources/converters/herrenberg/models.py

Resolves https://github.com/ParkenDD/parkapi-sources-v3/issues/131

fix Herrenberg parking type mapping

---

src/parkapi_sources/converters/kienzler/models.py

Solves the issue #138: kienzler attributes

#138 - Update data for static and realtime parking sites

---

src/parkapi_sources/converters/pbw/mapper.py
tests/converters/pbw_test.py

This ensures a valid public_url.

PWD parkplatz-finder link has changed

---

src/parkapi_sources/converters/apcoa/validators.py
src/parkapi_sources/converters/base_converter/pull/datex2_mixin.py
src/parkapi_sources/converters/base_converter/push/normalized_xlsx_converter.py
src/parkapi_sources/converters/karlsruhe/models.py
src/parkapi_sources/converters/neckarsulm_bike/converter.py
src/parkapi_sources/converters/p_m_bw/models.py
src/parkapi_sources/converters/reutlingen_bike/validation.py
src/parkapi_sources/converters/velobrix/models.py
src/parkapi_sources/models/parking_site_inputs.py
tests/converters/apcoa_test.py
tests/converters/huefner_test.py

This PR checks and ensures require attributes are available in the data.

Check required attributes

---

CHANGELOG.md
pyproject.toml
requirements-dev.txt
requirements.txt

version 0.17.0

---

docs/mapping/basics.md
docs/mapping/friedrichshafen_sensors.md

Adds a mapping definition for Friedrichshafen

friedrichshafen sensor model

---

dev/transform_utm32_geojson.py
pyproject.toml

Script for transforming UTM32 to WGS84 GeoJSON

UTM32 GeoJSON Transform Script

---

src/parkapi_sources/converters/base_converter/datex2/parking_record_status_validator.py
src/parkapi_sources/converters/base_converter/pull/__init__.py
src/parkapi_sources/converters/base_converter/pull/mobilithek_parking_site_pull_converter.py
src/parkapi_sources/converters/base_converter/pull/mobilithek_pull_converter.py
src/parkapi_sources/converters/friedrichshafen_sensors/converter.py

This MR fixes an issue with Mobilithek related pull mechanisms, which will enable a simpler handling based on base classes.

mobilithek pull mechanisms

---

src/parkapi_sources/converters/base_converter/datex2/datex2_static_mixin.py
src/parkapi_sources/converters/vrs/converter.py
tests/converters/data/vrs_bondorf-realtime.xml
tests/converters/data/vrs_bondorf-static.xml
tests/converters/data/vrs_kirchheim-realtime.xml
tests/converters/data/vrs_kirchheim-static.xml
tests/converters/data/vrs_neustadt-realtime.xml
tests/converters/data/vrs_neustadt-static.xml
tests/converters/vrs_test.py

Tests all VRS data and re-adds realtime data attribute to Datex2

Better Datex2 Testing

---

src/parkapi_sources/converters/friedrichshafen_sensors/converter.py
src/parkapi_sources/models/enums.py
src/parkapi_sources/models/parking_spot_inputs.py

Adds optional ParkingSpot.type

parking spot type

---

README.md
src/parkapi_sources/converters/apcoa/converter.py
src/parkapi_sources/converters/bahn_v2/converter.py
src/parkapi_sources/converters/base_converter/datex2/datex2_static_mixin.py
src/parkapi_sources/converters/base_converter/pull/pull_converter.py
src/parkapi_sources/converters/base_converter/pull/static_geojson_mixin.py
src/parkapi_sources/converters/bfrk_bw/base_converter.py
src/parkapi_sources/converters/freiburg/converter.py
src/parkapi_sources/converters/heidelberg/converter.py
src/parkapi_sources/converters/herrenberg/converter.py
src/parkapi_sources/converters/karlsruhe/converter.py
src/parkapi_sources/converters/kienzler/converter.py
src/parkapi_sources/converters/konstanz/converter.py
src/parkapi_sources/converters/opendata_swiss/converter.py
src/parkapi_sources/converters/p_m_bw/converter.py
src/parkapi_sources/converters/radvis_bw/converter.py
src/parkapi_sources/converters/velobrix/converter.py
src/parkapi_sources/converters/vrn_p_r/converter.py
src/parkapi_sources/models/__init__.py
src/parkapi_sources/models/parking_site_inputs.py
tests/conftest.py
tests/converters/data/patches/freiburg.json
tests/converters/freiburg_test.py

Parking Site Patch System for pull converters

parking site patch system

---

.pre-commit-config.yaml
README.md
pyproject.toml
requirements-dev.txt
requirements.txt
src/parkapi_sources/models/geojson_inputs.py
tests/util/data_xml_helper.py
tests/util/xml_helper_test.py

Various maintenance tasks in preparation of ParkAPI 0.19.0

maintenance tasks

---

README.md
pyproject.toml
src/parkapi_sources/converters/freiburg_disabled_sensors/converter.py
src/parkapi_sources/converters/freiburg_disabled_static/converter.py
src/parkapi_sources/converters/opendata_swiss/models.py
src/parkapi_sources/converters/ulm_sensors/converter.py
src/parkapi_sources/converters/velobrix/models.py
src/parkapi_sources/models/geojson_inputs.py
tests/converters/bietigheim_bissingen_test.py
tests/converters/helper.py

Properly addresses Freiburg converter with uids. Also fixes an issue with GeoJSON ParkingSpots.

various fixes

---

docs/mapping/reutlingen_disabled.md

Suggestion for reutlingen disabled mapping.

reutlingen disabled mapping

---

docs/mapping/karlsruhe_disabled.md

Karlsruhe disabled mapping proposal

karlsruhe disabled mapping

---

docs/mapping/freiburg_scanner.md

Freiburg provides data from scan cars

Freiburg scanner mapping

---

docs/mapping/ulm_disabled.md

Proposal for Ulm disabled mapping

ulm disabled mapping

---

docs/mapping/karlsruhe_disabled.md

Adds mapping details for karlsruhe disabled

karlsruhe disabled mapping fix

---

docs/mapping/heidelberg_disabled.md

heidelberg disabled mapping

---

src/parkapi_sources/converters/kienzler/converter.py
tests/converters/kienzler_geojson_test.py

... because we have a generic approach for this: the patching system

remove kienzler geojson

---

src/parkapi_sources/converters/bahn_v2/mapper.py

This PR adds the `park_and_ride_type` as `TRAIN` for all ParkingSites.

Bahn_v2: Add park_and_ride_type=TRAIN

---

src/parkapi_sources/converters/pbw/mapper.py
src/parkapi_sources/converters/pbw/validation.py
tests/converters/pbw_test.py

Determines PBW realtime data field based on input data

better pbw realtime data field

---

src/parkapi_sources/converters/base_converter/pull/pull_converter.py
src/parkapi_sources/models/parking_site_inputs.py
tests/converters/data/patches/parking_sites/freiburg.json
tests/converters/data/patches/parking_spots/freiburg_disabled_sensors.json
tests/converters/patching_test.py

... because typing was wrong there (dicts instead of dataclasses), which could end up into exceptions in follow up handling

fix patching system subobjects

---

docs/mapping/ladenburg_park_raum_check.md

ladenburg parkraumcheck
